version: "3.9"

services:
    postgres:
      image: postgres:16-alpine
      container_name: postgres
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        
    app:
      image: backend
      container_name: backend
      build:
          dockerfile: Dockerfile
          context: .
      command: gunicorn --bind 0.0.0.0:8000 --workers ${BACKEND_WORKERS_NUM} --worker-class uvicorn.workers.UvicornWorker backend.asgi
      volumes:
        - ./.env:/app/.env:ro
        - ./static:/static
        - ./media/:/media

      depends_on:
        - postgres
    
    nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
        - 80:80
        - 443:443
        - 8000:8000
      
      volumes:
        - ./frontend/dist:/share/frontend/:ro
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./certificates/:/cert/:ro
        - ./static/:/etc/nginx/html/static/:ro
        - ./media/:/etc/nginx/html/media/:ro

      depends_on:
        - app
